'use server'

import { auth } from '@clerk/nextjs/server'
import { prisma } from '@/lib/prisma'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'

export async function completeOnboarding(formData: {
  industry: string
  subIndustry: string
  yearsExperience: number
  skills: string[]
  bio: string
}) {
  const { userId } = await auth()

  if (!userId) {
    throw new Error('Unauthorized')
  }

  try {
    await prisma.$transaction(async (tx) => {
      // Update user profile
      await tx.user.update({
        where: { clerkId: userId },
        data: {
          industry: formData.industry,
          subIndustry: formData.subIndustry,
          yearsExperience: formData.yearsExperience,
          skills: formData.skills,
          bio: formData.bio,
          onboarded: true,
        },
      })

      // Check if industry exists, create if not
      let industry = await tx.industry.findUnique({
        where: { name: formData.industry },
      })

      if (!industry) {
        industry = await tx.industry.create({
          data: {
            name: formData.industry,
            subcategories: [formData.subIndustry],
          },
        })
      } else if (!industry.subcategories.includes(formData.subIndustry)) {
        await tx.industry.update({
          where: { id: industry.id },
          data: {
            subcategories: [...industry.subcategories, formData.subIndustry],
          },
        })
      }

      // Check if industry insights exist
      const existingInsight = await tx.industryInsight.findUnique({
        where: {
          industryId_subIndustry: {
            industryId: industry.id,
            subIndustry: formData.subIndustry,
          },
        },
      })

      if (!existingInsight) {
        // Create placeholder insights (will be generated by AI later)
        await tx.industryInsight.create({
          data: {
            industryId: industry.id,
            subIndustry: formData.subIndustry,
            marketOutlook: 'neutral',
            growthRate: 0,
            demandLevel: 'Medium',
            topSkills: [],
            recommendedSkills: [],
            keyTrends: [],
            salaryRanges: {},
            nextUpdate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
          },
        })
      }
    })

    revalidatePath('/dashboard')
  } catch (error) {
    console.error('Error completing onboarding:', error)
    throw new Error('Failed to complete onboarding')
  }

  redirect('/dashboard')
}

export async function getUser() {
  const { userId } = await auth()

  if (!userId) {
    return null
  }

  const user = await prisma.user.findUnique({
    where: { clerkId: userId },
  })

  return user
}
